### ISSUE TITLE
Javascript error on page load

### ISSUE THREAD

**Issue by EleanorRagone** [roberdam/Xaddress#1]
Google Maps API error: RefererNotAllowedMapError https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: http://xaddress.org/try?lng=en

**Comment by roberdam** [comment]
Thanks Peter,
Can you try http://www.xaddress.org/try?lng=en instead?

**Comment by EleanorRagone** [comment]
Yeah that URL works.

However, there's a separate issue of the mouse disappearing whenever it is over (well, I guess "under" would be more accurate) the map.  Want a separate issue filed for that?

**Comment by roberdam** [comment]
yes please!, thanks again!

**Comment by roberdam** [comment]
Google maps require now that you use a API key to use the maps, and whitelist domains that will be allowed to use that API key, even when http://xaddress.org is whitelisted, somethimes you need to use the full url http://www.xaddress.org
