### ISSUE TITLE
Google maps API errror

### ISSUE THREAD

**Issue by harry-wood** [roberdam/Xaddress#14]
I'm seeing Google Maps API errors on the "Try it" map. Looks as if the google API key isn't set up properly.

![screen shot 2016-08-11 at 09 56 03](https://cloud.githubusercontent.com/assets/227525/17583677/09d96e94-5faa-11e6-9fea-ca1b9d3156da.png)

This seemed to be fixed last night and now it's broken again.

p.s. You should [switch2osm](https://switch2osm.org/) anyway

**Comment by roberdam** [comment]
Thanks Harry, 
Can you try with http://www.xaddress.org/try?lng=en and let me know please if that fix the problem?
Thanks for the suggestion, I would love to use Openmaps, but there are no satellite photos.

**Comment by roberdam** [comment]
Please let me know if you have any further problems!.
