### ISSUE TITLE
Explanation of Encoding/Decoding

### ISSUE THREAD

**Issue by lucanos** [roberdam/Xaddress#16]
This system is touted as allowing for addresses to be Encoded/Decoded Offline, but the logic which allows this to happen is not explained. I'd love to better understand how this actually works.

**Comment by roberdam** [comment]
Hi Luke,
You can check it on https://github.com/roberdam/Xaddress/tree/master/by_hand

**Comment by roberdam** [comment]
Let me know if you need anything else.
