### ISSUE TITLE
Make a logo that doesnt steal Mesosphere's graphics

### ISSUE THREAD

**Issue by kplimack** [roberdam/Xaddress#17]
thats low

**Comment by roberdam** [comment]
can you let me know what is the graphics you refer to?

**Comment by roberdam** [comment]
if you are talking about https://cloud.githubusercontent.com/assets/3354868/17249828/b7e84ef0-556f-11e6-80e7-10bd51c46143.png 
Is not a logo, is cropped printscreen of the website, the patterns that shows there are random.
