### ISSUE TITLE
How to generate a table for a country (PF) ?

### ISSUE THREAD

**Issue by teriiehina** [roberdam/Xaddress#19]
Hi,

really interested in this work and I would like to contribute.

I'm a polynesian from French Polynesia (PF).
I wanted to play a bit with Xaddress but couldn't find the table for my country, even if it is referenced in the [countries.csv](https://github.com/roberdam/Xaddress/blob/master/countries.csv#L20) and the [states.csv](https://github.com/roberdam/Xaddress/blob/master/states.csv#L359) file.

What should/can I do to generate the table for French polynesia ?

**Comment by roberdam** [comment]
Hi Peter, 
Sorry about that, I just uploaded the PF.pdf table, 
https://github.com/roberdam/Xaddress/blob/master/by_hand/tables/PF.pdf
let me know if you have any other issue 
Great weekend! @teriiehina

**Comment by teriiehina** [comment]
Hi @roberdam,

thank you, everything is complete for me to play for xaddress. hope to have something fun to show by the end of the week-end.

Great week-end to yoo too :)

**Comment by roberdam** [comment]
I can't wait to see it :D
