### ISSUE TITLE
Documentation Request: Encoding/Decoding Algorithm

### ISSUE THREAD

**Issue by spidergears** [roberdam/Xaddress#20]
Can you provide some documentation around encoding and decoding algorithms.
The process for encoding the latlng, by-hand looks significantly different from what is used in Ruby encoder. Since most variable names and function names are in Spanish (I guess), comprehending the meaning is a bit difficult.

**Comment by roberdam** [comment]
Of course, I will make a pseudocode step by step guide to port xaddress on any language tomorrow using actual tables so you dont have to rely on the ruby code

**Comment by roberdam** [comment]
@spidergears @elpoisterio here is the pseudocode guide for decoding https://github.com/roberdam/Xaddress/blob/master/pseudocode/decode
I will work on the encode now, please let me know if is clear enough or if you need something else.

**Comment by spidergears** [comment]
lgtm, I will let you know I if i don't understand anything. Thanks.

**Comment by roberdam** [comment]
Encode added, you can open again the issue on any question.
