### ISSUE TITLE
Query: How about adding the Crown Dependencies of UK as countries to countries csv?

### ISSUE THREAD

**Issue by spidergears** [roberdam/Xaddress#21]
I am trying to setup `sqlite-db` for use with Android app. I want all entries in `states` table to refer to a country in `countries` table (as `foreign key`).
The entries for Crown dependencies of the United Kingdom (pseudo-countries) Guernsey(GG), Isle of Man(IM) and Jersey(JE) do not show up in `countries.csv` file.

For the sake of consistency, I suggest we add these to `countries.csv`.

This way these pseudo-countries also show up in drop-down for countries, making lives easy for everyone.

I don't  a reason for not including them in the list of countries. 

PS: I am not aware any technical issues change might pose.

**Comment by roberdam** [comment]
Thanks @spidergears I will work on that , hopefully tomorrow will be ready.

**Comment by roberdam** [comment]
Added GG,IM,JE, let me know any other issue!
