### ISSUE TITLE
API plans?

### ISSUE THREAD

**Issue by atonb117** [roberdam/Xaddress#22]
I was wondering if you had any plans to make, or already made, this available as public API that companies can call instead of running their own instance?

Apologies if I missed something basic.

Great project!

**Comment by roberdam** [comment]
Thanks for the suggestion @atonb117 , yes an API is being developed.
In the meanwhile you can check the pseudocode guide to implement the algorithm that was published yesterday https://github.com/roberdam/Xaddress/tree/master/pseudocode 
Let me know if is clear enough!

**Comment by atonb117** [comment]
Looks simple enough, I just don't have time to write it up in Node.  But I'll keep checking back!  Great work!

**Comment by roberdam** [comment]
Check this out 
https://www.npmjs.com/package/xaddress
