### ISSUE TITLE
Xaddress.org is down

### ISSUE THREAD

**Issue by HalosGhost** [roberdam/Xaddress#28]
Hello! It looks like xaddress.org is now failing to function (redirect issues, it seems). I didn't know where else to report the issue, but I'm very excited about xaddress, and figured I should at least report the outage in case it had gone unnoticed.

**Comment by roberdam** [comment]
Thanks for the report and sorry for the delay, it should be working now, let me know if you have any issues!

**Comment by HalosGhost** [comment]
@roberdam, it actually still looks down to me.

**Comment by roberdam** [comment]
Can you try
https://xaddress.org/try?lng=en

**Comment by HalosGhost** [comment]
@roberdam, looks up to me now!
