### ISSUE TITLE
Incorrect country reported

### ISSUE THREAD

**Issue by jamesacraig** [roberdam/Xaddress#4]
[image](https://cloud.githubusercontent.com/assets/20950716/17556406/38e99776-5f0b-11e6-9484-44957f41c894.png)
When selecting my home on the map (search google maps for G12 9AD, Glasgow, UK) it reports the country as Ukraine, as shown in the image attached.

**Comment by roberdam** [comment]
Thanks James, 
I will check in to that!.

**Comment by roberdam** [comment]
Sorry for the delay on fixing this James, it should be already working, let me know if you have any other issue!
