### ISSUE TITLE
Use secure origin

### ISSUE THREAD

**Issue by mholt** [roberdam/Xaddress#8]
Hey Rober, neat project! The page with the map (http://xaddress.org/try?lng=en) needs HTTPS in order for geolocation to work successfully in modern browsers like the newest versions of Chrome.  This is because they don't want to allow snoopers to get people's physical locations, since that geolocation data is almost always transmitted over the network.

**Comment by roberdam** [comment]
Thanks Matt!
I put the website with HTTPS but roll back again by now, the website uses third party APIs that does not support HTTPS (not for the free version), also im using another server with plain ip addresses to manage the encoding/decoding part so I need to buy a dummy domain and HTTPS that server too.
In the meanwhile I will disable the getCurrentPosition() and watchPosition() functions to get ride errors in the console.

**Comment by mholt** [comment]
Alright, cool, thanks for your work!

**Comment by roberdam** [comment]
Thank you for your suggestions!
